const requests = (projectID, path, limit, page) => {
  return {
    status: 200,
    data: {
      pagination: {
        next: `${page < 5 && `${path}?limit=${limit}&page=${page + 1}`}`,
        previous: `${page > 1 && `${path}?limit=${limit}&page=${page - 1}`}`,
        total: limit * 5,
        total_pages: 5,
      },
      pull_requests: [
        {
          type: 'google_compute_firewall',
          name: 'test-6-24-3',
          status: 'Complete',
          status_details: '',
          requester: 'JOHN SMITH',
          requested_at: '2021-09-24T20:52:01Z',
          contact_info: 'jsmith@xyz.com',
          pr_number: 117,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/87`,
        },
        {
          type: 'google_compute_firewall',
          name: 'test-6-24-2',
          status: 'Complete',
          status_details: '',
          requester: 'JANE SMITH',
          requested_at: '2021-09-24T19:42:17Z',
          contact_info: 'j_smith@xyz.com',
          pr_number: 106,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/76`,
        },
        {
          type: 'google_compute_firewall',
          name: 'test-6-24',
          status: 'Complete',
          status_details: '',
          requester: 'JOHN SMITH',
          requested_at: '2021-09-24T19:05:39Z',
          contact_info: 'jsmith@xyz.com',
          pr_number: 95,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/75`,
        },
        {
          type: 'google_project_iam_binding',
          name: 'roles_storagetransfer-admin',
          status: 'Complete',
          status_details: '',
          requester: 'JANE DOE',
          requested_at: '2021-09-21T16:49:36Z',
          contact_info: 'jdoe@xyz.com',
          pr_number: 84,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/44`,
        },
        {
          type: 'google_compute_firewall',
          name: 'test-1',
          status: 'Complete',
          status_details: '',
          requester: 'JOHN DOE',
          requested_at: '2021-09-16T16:06:19Z',
          contact_info: 'j_doe@xyz.com',
          pr_number: 83,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/43`,
        },
        {
          type: 'google_project_iam_binding',
          name: 'roles_bigquery.jobUser',
          status: 'Complete',
          status_details: '',
          requester: 'JANE SMITH',
          requested_at: '2021-05-07T23:35:40Z',
          contact_info: 'j_smith@xyz.com',
          pr_number: 77,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/3`,
        },
        {
          type: 'google_compute_firewall',
          name: 'sarah-demo-rule01',
          status: 'Complete',
          status_details: '',
          requester: 'JANE SMITH',
          requested_at: '2020-12-17T19:25:42Z',
          contact_info: 'j_smith@xyz.com',
          pr_number: 1,
          pr_url: `https://github.com/tfe-workspaces/${projectID}/pull/2`,
        },
      ],
    },
  };
};

module.exports = requests;
